### ISSUE TITLE
*string to nil if empty string

### ISSUE THREAD

**Issue by frederikhors** [go-playground/mold#10]
Let's say I have this struct:

```go
type User struct {
  Username *string
}
```

and I need to sanitize it from empty string: I want `Username` to be `nil` if is an empty string (maybe because previous modifiers made it empty).

Is it correct to do this with this package?

**Comment by frederikhors** [comment]
I think this is the same, right?

Let's say I have this struct:

```go
type User struct {
  Username *string
}
```

and I need to sanitize it from empty string as username, I want `Username` to be `nil`.

Is it correct to do this with this package?

**Comment by frederikhors** [comment]
I think this is the same, right? https://github.com/asaskevich/govalidator/pull/329

**Comment by frederikhors** [comment]
I'm stuck.

**Reproduction**: https://play.golang.org/p/_DlluqE2Y3k

```go
package main

import (
	"context"
	"fmt"
	"log"
	"reflect"

	"github.com/go-playground/mold/v3"
)

var tform *mold.Transformer

func main() {
	tform = mold.New()
	tform.Register("nilEmptyString", nilEmptyString)

	type Test struct {
		String *string `mold:"nilEmptyString"`
	}

	myEmptyString := ""
	tt := Test{String: &myEmptyString}

	err := tform.Struct(context.Background(), &tt)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%+v\n", tt)

	var myString string
	err = tform.Field(context.Background(), &myString, "nilEmptyString")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(myString)
}

func nilEmptyString(_ context.Context, _ *mold.Transformer, v reflect.Value, _ string) error {
	s, ok := v.Interface().(*string)
	if !ok { // ok is always false, why?
		return nil
	}

	if s != nil && *s != "" {
		return nil
	}

	if s != nil && *s == "" {
		v.SetPointer(nil)
	}

	// v.Set(nil) // how to do this?

	return nil
}
```

1. Why `ok` in `s, ok := v.Interface().(*string)` is always false?

1. How to set `v` to `nil`? Why is `v.Set(nil)` wrong?

Can you help me understand, please?

**Comment by frederikhors** [comment]
@deankarn, I know that the new home could be a perfect enemy for our 20/24 a day PC habits 😄 but can I ask you to just unlock me on this problem/feature?

So I can use mold in my project right now as long as you calmly close the other PRs.

Thank you so much!

❤️

**Comment by deankarn** [comment]
I will try to take a look at this tonight after work for you @frederikhors

**Comment by frederikhors** [comment]
I'll continue with other PRs and conflicts. But please do not forget about this: it's very important for me. 😅

**Comment by deankarn** [comment]
@frederikhors I looked into this and it is doable, BUT, I'm going to have to change the modifier function signature...a breaking change.

currently I extract the underlying value for manipulation, but to set the value of the pointer you need the parent value which I currently do not pass along to the function.

once I do though you'll be able to set the parent like so:
```go
v.Set(reflect.Zero(parent.Type()))
```

Example, I pass `current` to the function but not `orig` which is needed to accomplish what you want.
```go
func (t *Transformer) setByField(ctx context.Context, orig reflect.Value, ct *cTag) (err error) {
	current, kind := extractType(orig)

	if ct != nil && ct.hasTag {
		for ct != nil {
			switch ct.typeof {
			case typeEndKeys:
				return
			case typeDive:
				ct = ct.next

				switch kind {
				case reflect.Slice, reflect.Array:
					err = t.setByIterable(ctx, current, ct)
				case reflect.Map:
					err = t.setByMap(ctx, current, ct)
				default:
					err = ErrInvalidDive
				}
				return

			default:
				if !current.CanAddr() {
					newVal := reflect.New(current.Type()).Elem()
					newVal.Set(current)
					if err = ct.fn(ctx, t, newVal, ct.param); err != nil {
						return
					}
					orig.Set(newVal)
				} else {
					if err = ct.fn(ctx, t, current, ct.param); err != nil {
						return
					}
				}
				ct = ct.next
			}
		}
	}
```

Since more params are being passed and I don't want to make another breaking change after this I'm going to pass an interface to the functions like I do in `validator` to future proof it a bit. This may take me a bit to implement as I want to get it right.

**Comment by deankarn** [comment]
FYI @frederikhors initial changes made https://github.com/go-playground/mold/tree/change-function-interface

will let them sit with me for a few days before merging, would also love your opinion on the new interface.

**Comment by frederikhors** [comment]
I think I like it.

**Comment by deankarn** [comment]
v4 release complete and this is now possible.
