### ISSUE TITLE
Probable bugs

### ISSUE THREAD

**Issue by frederikhors** [go-playground/mold#19]
![image](https://user-images.githubusercontent.com/41120635/101364224-9e805500-38a2-11eb-9db4-daae12837999.png)

These lines: https://github.com/go-playground/mold/blob/master/mold.go#L286-L296

Warnings by Goland (JetBrains):

`Accessing field `ct.keys` may lead to nil pointer dereference`
`Accessing field `ct.next` may lead to nil pointer dereference`

**Comment by deankarn** [comment]
although technically true from the eyes of a linter, ct is in fact always set in these cases during the parsing and caching logic; can't believe everything the linters tell you ;)

but I can silence then with a nil check if necessary.

**Comment by frederikhors** [comment]
> but I can silence then with a nil check if necessary.

I will prefer. Thank you very much.

**Comment by deankarn** [comment]
refactored in v4 release.
