### ISSUE TITLE
question: plans to port validator on top of this?

### ISSUE THREAD

**Issue by ansel1** [go-playground/mold#2]
Seems like the Transform is a refactoring of the basic struct traversal logic from validator.  Was thinking it would be really useful to have a re-usable struct visitor library like this, to build focussed struct processing packages, like one which sets default values, initializes values from environment variables, or validates.

One thing I see missing from mold, which validator uses, is that the Func doesn't know where it is in the hierarchy, so it isn't possible to include that information in error messages or validation problems.  

I'm interested in the idea of building other types of struct processors on top of this core because I use a number of them currently, and they are all slightly different in how they work.  For example, whether they allow setting the tag name, what they do with fields with no tags, how many tag names that package uses, how they traverse embedded structs, which types they handle, etc.  Would be really nice to have a core traversal logic which encouraged some patterns, like one (configurable) tag per package/processor, consistent handling of untagged fields, etc.

**Comment by joeybloggs** [comment]
Hey @ansel1 Transform is more like if [form](https://github.com/go-playground/form) and [validator](https://github.com/go-playground/validator) had a code baby ;)

I had the same thought after creating this library, I just haven't been able to think of a way to consolidate the logic as libraries that need to set data, like form and mold, vs only need to read, like validator, behave very differently eg. https://github.com/go-playground/mold/blob/v2/mold.go#L230-L253

not to mention the caching layers are completely different, even though they do share a lot of information.

then there's differentiating between errors eg. is it a Validation vs Set

and consolidating to one tag might not be as straightforward as that, what if I wanted to skip validation, but not the set of data from say an ENV variable?

I'm sure it could be done somehow, however, I'm not sure that I want to as each of the libraries works great independently and can be configured independently and in any configuration/order you want to.

let me think about it for a while though I might be able to make it all come together.

**Comment by ansel1** [comment]
I wonder if the differences between read/write cases, and cases where the Funcs needed context information, could be consolidated by adding an arg (or replacing the args) to Func to take a mold.Context kind of thing, sort of like the arg that validator custom funcs take, but more general purpose.

Re: types of errors, it seems like it would be sufficient to handle errors the way mold does: an error means abort immediately.  It's simple and easy to understand.  Maybe add a sentinel ErrStop which terminates traversal but not return an error to the caller.  Other than that, for cases like validation packages, where the package wants to accumulate problems (or other information), it would be up to the library to do that, accumulating it in some object attached to the context (either the context.Context, or a mold.Context if you add that notion).

> and consolidating to one tag might not be as straightforward as that, what if I wanted to skip validation, but not the set of data from say an ENV variable?

I didn't mean to consolidate multiple functions into a single struct tag.  I meant, it would be nice if  each struct processing package did one and only one thing (like validation, or reading env variables, or setting defaults), and only used one tag for itself.  That makes it easier to mix and match different packages for different functions.  Was looking at the https://github.com/kelseyhightower/envconfig package: it uses the tags `envconfig`, `required`, `default`, and `split_words`.  I use other packages which use some of those same tags.  You can't change the tag name, or disable processing some of those tags...doesn't play well with others.
