### ISSUE TITLE
Support for more transformers like "max length" on string etc

### ISSUE THREAD

**Issue by mattwelke** [go-playground/mold#4]
I'm coming from a Node.js background. My company is switching a lot of text processing stuff from Node to Go and we're looking for validation and sanitization libraries.

We used to use a library called "schema-inspector"
 (https://www.npmjs.com/package/schema-inspector) which broke this into two steps. They have a "sanitize" step where the rules are used to modify the data. Then they have a "validate" step where if the data doesn't fit the rule, it throws an error. We use this for strings with rules like "max length". For example, if you have a rule where the `username` property has a max length of 5 and this object:

```
{
  "username": "bobbytables"
}
```

then after the sanitize step, you'll end up with this object:

```
{
  "username": "bobby"
}
```

And then after the validate step, this would pass because the data has been transformed to meet the rule during the sanitization step. Usually situations where the data would pass sanitization but fail validation are when you've got broad rules like "max length on a string" in the sanitize step but more focussed rules like a regexp match on the validate step.

I was wondering if as the library authors, you are willing to accept PRs to add these features? I notice the following source code in the library:

```
// New returns a modifier with defaults registered
func New() *mold.Transformer {
	mod := mold.New()
	mod.SetTagName("mod")
	mod.Register("trim", TrimSpace)
	mod.Register("ltrim", TrimLeft)
	mod.Register("rtrim", TrimRight)
	mod.Register("tprefix", TrimPrefix)
	mod.Register("tsuffix", TrimSuffix)
	mod.Register("lcase", ToLower)
	mod.Register("ucase", ToUpper)
	mod.Register("snake", SnakeCase)
	return mod
}
```

This is really simple to understand even as a Go novice. I can see how I would extend this by adding more modules I can register. There could be a module added to handle trimming based on a max length for example. If you're willing to accept PRs, I can direct the work here instead of us rolling our own.

Looking forward to hearing back from you!

**Comment by joeybloggs** [comment]
@welkie yes I’d be happy to accept some PR’s

As a side note you can break the sanitization and validation steps up by using this lib and the validation library found in this org also.

**Comment by welkie** [comment]
@joeybloggs Thanks for the quick response. That approach, using this library with the validation library in this org is exactly what I was thinking of doing. It was just a matter of adding the features we need to this library or rolling our own. Either way, the validation library looks super impressive and we plan on using it. :+1:

**Comment by deankarn** [comment]
Closing for now, happy to accept PR's for v4 release
